/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:13:34 GMT 2020
 */

package com.capitalone.dashboard.model.score.settings;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.score.settings.ScoreCriteria;
import com.capitalone.dashboard.model.score.settings.ScoreThresholdSettings;
import com.capitalone.dashboard.model.score.settings.ScoreType;
import com.capitalone.dashboard.model.score.settings.ScoreTypeValue;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScoreCriteria_ESTest extends ScoreCriteria_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      ScoreTypeValue scoreTypeValue0 = new ScoreTypeValue();
      scoreCriteria0.setNoWidgetFound(scoreTypeValue0);
      ScoreTypeValue scoreTypeValue1 = scoreCriteria0.getNoWidgetFound();
      assertSame(scoreTypeValue1, scoreTypeValue0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      ScoreTypeValue scoreTypeValue0 = new ScoreTypeValue();
      ScoreType scoreType0 = ScoreType.no_score;
      scoreTypeValue0.setScoreType(scoreType0);
      scoreCriteria0.setNoDataFound(scoreTypeValue0);
      ScoreTypeValue scoreTypeValue1 = scoreCriteria0.getNoDataFound();
      assertTrue(scoreTypeValue1.isNoScore());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      ScoreTypeValue scoreTypeValue0 = new ScoreTypeValue();
      scoreCriteria0.setNoDataFound(scoreTypeValue0);
      ScoreTypeValue scoreTypeValue1 = scoreCriteria0.getNoDataFound();
      assertFalse(scoreTypeValue1.isNoScore());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      LinkedList<ScoreThresholdSettings> linkedList0 = new LinkedList<ScoreThresholdSettings>();
      scoreCriteria0.setDataRangeThresholds(linkedList0);
      List<ScoreThresholdSettings> list0 = scoreCriteria0.getDataRangeThresholds();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      ScoreTypeValue scoreTypeValue0 = scoreCriteria0.getNoDataFound();
      assertNull(scoreTypeValue0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      List<ScoreThresholdSettings> list0 = scoreCriteria0.getDataRangeThresholds();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      ScoreTypeValue scoreTypeValue0 = ScoreTypeValue.noScore();
      scoreCriteria0.setNoWidgetFound(scoreTypeValue0);
      ScoreTypeValue scoreTypeValue1 = scoreCriteria0.getNoWidgetFound();
      assertTrue(scoreTypeValue1.isNoScore());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      ScoreTypeValue scoreTypeValue0 = scoreCriteria0.getNoWidgetFound();
      assertNull(scoreTypeValue0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = ScoreCriteria.cloneScoreCriteria((ScoreCriteria) null);
      assertNull(scoreCriteria0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      String string0 = scoreCriteria0.toString();
      assertEquals("ScoreCriteria{noWidgetFound=null, noDataFound=null, dataRangeThresholds=null}", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      // Undeclared exception!
      try { 
        ScoreCriteria.cloneScoreCriteria(scoreCriteria0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/collections/CollectionUtils
         //
         verifyException("com.capitalone.dashboard.model.score.settings.ScoreCriteria", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ScoreCriteria scoreCriteria0 = new ScoreCriteria();
      LinkedList<ScoreThresholdSettings> linkedList0 = new LinkedList<ScoreThresholdSettings>();
      scoreCriteria0.setDataRangeThresholds(linkedList0);
      ScoreThresholdSettings scoreThresholdSettings0 = new ScoreThresholdSettings();
      linkedList0.add(scoreThresholdSettings0);
      List<ScoreThresholdSettings> list0 = scoreCriteria0.getDataRangeThresholds();
      assertTrue(list0.contains(scoreThresholdSettings0));
  }
}
