/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:01:41 GMT 2020
 */

package com.capitalone.dashboard.model.webhook.github;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.webhook.github.MergeEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MergeEvent_ESTest extends MergeEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergedAt(1681L);
      long long0 = mergeEvent0.getMergedAt();
      assertEquals(1681L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergedAt((-2330L));
      long long0 = mergeEvent0.getMergedAt();
      assertEquals((-2330L), long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeSha("CAIJDFus");
      String string0 = mergeEvent0.getMergeSha();
      assertEquals("CAIJDFus", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeRef("");
      String string0 = mergeEvent0.getMergeRef();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeAuthorLDAPDN("uOy");
      String string0 = mergeEvent0.getMergeAuthorLDAPDN();
      assertEquals("uOy", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeAuthorLDAPDN("");
      String string0 = mergeEvent0.getMergeAuthorLDAPDN();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeAuthor("da!=m4(v%NS['O");
      String string0 = mergeEvent0.getMergeAuthor();
      assertEquals("da!=m4(v%NS['O", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setGitRequestNumber("y");
      String string0 = mergeEvent0.getGitRequestNumber();
      assertEquals("y", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setGitRequestNumber("");
      String string0 = mergeEvent0.getGitRequestNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      String string0 = mergeEvent0.getMergeSha();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      String string0 = mergeEvent0.getMergeAuthor();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeAuthor("hZG4/VpDu:%rem<A'n");
      MergeEvent mergeEvent1 = new MergeEvent();
      boolean boolean0 = mergeEvent0.equals(mergeEvent1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      MergeEvent mergeEvent1 = new MergeEvent();
      assertTrue(mergeEvent1.equals((Object)mergeEvent0));
      
      mergeEvent1.setGitRequestNumber("");
      boolean boolean0 = mergeEvent0.equals(mergeEvent1);
      assertFalse(mergeEvent1.equals((Object)mergeEvent0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      MergeEvent mergeEvent1 = new MergeEvent();
      mergeEvent1.setMergeSha("");
      boolean boolean0 = mergeEvent0.equals(mergeEvent1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      MergeEvent mergeEvent1 = new MergeEvent();
      boolean boolean0 = mergeEvent0.equals(mergeEvent1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      boolean boolean0 = mergeEvent0.equals(mergeEvent0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      boolean boolean0 = mergeEvent0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeAuthor("");
      String string0 = mergeEvent0.getMergeAuthor();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeRef("com.capitalone.dashboard.model.webhook.github.MergeEvent");
      String string0 = mergeEvent0.getMergeRef();
      assertEquals("com.capitalone.dashboard.model.webhook.github.MergeEvent", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.setMergeSha("");
      String string0 = mergeEvent0.getMergeSha();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      mergeEvent0.hashCode();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      String string0 = mergeEvent0.getMergeAuthorLDAPDN();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      String string0 = mergeEvent0.getMergeRef();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      String string0 = mergeEvent0.getGitRequestNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MergeEvent mergeEvent0 = new MergeEvent();
      long long0 = mergeEvent0.getMergedAt();
      assertEquals(0L, long0);
  }
}
