/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 10:06:54 GMT 2020
 */

package com.capitalone.dashboard.model.quality;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.runner.RunWith;

public class ArtifactType_ESTest{
	

	@Test
	public void test1() {
		ArtifactType type=ArtifactType.checkstyle;
		assertEquals(ArtifactType.valueOf("checkstyle"), type);  
	}
	@Test
	public void test2() {
		ArtifactType type=ArtifactType.junit;
		assertEquals(ArtifactType.valueOf("junit"), type);  
	}
	@Test
	public void test3() {
		ArtifactType type=ArtifactType.jacoco;
		assertEquals(ArtifactType.valueOf("jacoco"), type);  
	}
	@Test
	public void test4() {
		ArtifactType type=ArtifactType.pmd;
		assertEquals(ArtifactType.valueOf("pmd"), type);  
	}
	@Test
	public void test5() {
		ArtifactType type=ArtifactType.findbugs;
		assertEquals(ArtifactType.valueOf("findbugs"), type);  
	}
	
}
