/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 10:06:49 GMT 2020
 */

package com.capitalone.dashboard.model.quality;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.quality.CheckstyleReport;
import com.capitalone.dashboard.model.quality.QualityVisitor;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;

public class CheckstyleReport_ESTest {

	/*
	 * @Test(timeout = 4000) public void test0() throws Throwable { CheckstyleReport
	 * checkstyleReport0 = new CheckstyleReport(); QualityVisitor<Integer>
	 * qualityVisitor0 = (QualityVisitor<Integer>) mock(QualityVisitor.class, new
	 * ViolatedAssumptionAnswer()); checkstyleReport0.accept(qualityVisitor0); }
	 */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CheckstyleReport.CheckstyleFile checkstyleReport_CheckstyleFile0 = new CheckstyleReport.CheckstyleFile();
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      LinkedList<CheckstyleReport.CheckstyleFile> linkedList0 = new LinkedList<CheckstyleReport.CheckstyleFile>();
      linkedList0.add(checkstyleReport_CheckstyleFile0);
      checkstyleReport0.setFiles(linkedList0);
      List<CheckstyleReport.CheckstyleFile> list0 = checkstyleReport0.getFiles();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CheckstyleReport.CheckstyleFile checkstyleReport_CheckstyleFile0 = new CheckstyleReport.CheckstyleFile();
      List<CheckstyleReport.CheckstyleError> list0 = checkstyleReport_CheckstyleFile0.getErrors();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CheckstyleReport.CheckstyleFile checkstyleReport_CheckstyleFile0 = new CheckstyleReport.CheckstyleFile();
      checkstyleReport_CheckstyleFile0.setErrors((List<CheckstyleReport.CheckstyleError>) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CheckstyleReport.CheckstyleError checkstyleReport_CheckstyleError0 = new CheckstyleReport.CheckstyleError();
      CheckstyleReport.CheckstyleSeverity checkstyleReport_CheckstyleSeverity0 = checkstyleReport_CheckstyleError0.getSeverity();
      checkstyleReport_CheckstyleError0.setSeverity(checkstyleReport_CheckstyleSeverity0);
      assertNull(checkstyleReport_CheckstyleError0.getSeverity());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      LinkedList<CheckstyleReport.CheckstyleFile> linkedList0 = new LinkedList<CheckstyleReport.CheckstyleFile>();
      checkstyleReport0.setFiles(linkedList0);
      List<CheckstyleReport.CheckstyleFile> list0 = checkstyleReport0.getFiles();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      // Undeclared exception!
      try { 
        checkstyleReport0.accept((QualityVisitor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.capitalone.dashboard.model.quality.CheckstyleReport", e);
      }
  }

  private void verifyException(String string, NullPointerException e) {
	// TODO Auto-generated method stub
	
}

@Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      List<CheckstyleReport.CheckstyleFile> list0 = checkstyleReport0.getFiles();
      assertNull(list0);
  }
}
