/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 10:08:29 GMT 2020
 */

package com.capitalone.dashboard.model.quality;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.quality.JunitXmlReport;
import com.capitalone.dashboard.model.quality.QualityVisitor;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import org.junit.runner.RunWith;

public class JunitXmlReport_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = new JunitXmlReport.Testcase.Failure();
      junitXmlReport_Testcase_Failure0.setValue("com.capitalone.dashboard.model.quality.JunitXmlReport$Testcase$Failure");
      String string0 = junitXmlReport_Testcase_Failure0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = new JunitXmlReport.Testcase.Failure();
      junitXmlReport_Testcase_Failure0.setMessage("com.capitalone.dashboard.model.quality.JunitXmlReport$Testcase$Failure");
      String string0 = junitXmlReport_Testcase_Failure0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = new JunitXmlReport.Testcase.Failure();
      junitXmlReport_Testcase_Failure0.setValue(";VZ");
      String string0 = junitXmlReport_Testcase_Failure0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = new JunitXmlReport.Testcase.Failure();
      junitXmlReport_Testcase_Failure0.setType("KhzfDVv}j");
      String string0 = junitXmlReport_Testcase_Failure0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      junitXmlReport_Testcase0.error = junitXmlReport_Testcase_Error0;
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error1 = junitXmlReport_Testcase0.getError();
      junitXmlReport_Testcase_Error1.type = "%_rSbk#QMo-";
      String string0 = junitXmlReport_Testcase_Error1.getType();
      assertEquals("%_rSbk#QMo-", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      junitXmlReport_Testcase_Error0.value = "";
      String string0 = junitXmlReport_Testcase_Error0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setName("");
      String string0 = junitXmlReport_Testcase0.getSkipped();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setClassname("8");
      String string0 = junitXmlReport_Testcase0.getSkipped();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setClassname("");
      String string0 = junitXmlReport_Testcase0.getClassname();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JunitXmlReport.Properties.Property junitXmlReport_Properties_Property0 = new JunitXmlReport.Properties.Property();
      junitXmlReport_Properties_Property0.setName("");
      String string0 = junitXmlReport_Properties_Property0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JunitXmlReport.Properties.Property junitXmlReport_Properties_Property0 = new JunitXmlReport.Properties.Property();
      junitXmlReport_Properties_Property0.setName("");
      String string0 = junitXmlReport_Properties_Property0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      BigInteger bigInteger0 = BigInteger.ZERO;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      junitXmlReport0.setTime(bigDecimal0);
      BigDecimal bigDecimal1 = junitXmlReport0.getTime();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      BigDecimal bigDecimal0 = new BigDecimal((-745L));
      junitXmlReport0.time = bigDecimal0;
      BigDecimal bigDecimal1 = junitXmlReport0.getTime();
      assertEquals((short) (-745), bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      BigDecimal bigDecimal0 = new BigDecimal(5323L);
      junitXmlReport0.setTime(bigDecimal0);
      BigDecimal bigDecimal1 = junitXmlReport0.getTime();
      assertEquals((byte) (-53), bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.tests = 5;
      int int0 = junitXmlReport0.getTests();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setTests((-2466));
      int int0 = junitXmlReport0.getTests();
      assertEquals((-2466), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      LinkedList<JunitXmlReport.Testcase> linkedList0 = new LinkedList<JunitXmlReport.Testcase>();
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      linkedList0.add(junitXmlReport_Testcase0);
      junitXmlReport0.testcase = (List<JunitXmlReport.Testcase>) linkedList0;
      List<JunitXmlReport.Testcase> list0 = junitXmlReport0.getTestcase();
      assertTrue(list0.contains(junitXmlReport_Testcase0));
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSystemOut("r88K='Phc^xJM1ILwT");
      String string0 = junitXmlReport0.getSystemOut();
      assertEquals("r88K='Phc^xJM1ILwT", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSystemOut("");
      String string0 = junitXmlReport0.getSystemOut();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.systemErr = "";
      String string0 = junitXmlReport0.getSystemErr();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSkips(".git");
      String string0 = junitXmlReport0.getSkips();
      assertEquals(".git", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSkips("");
      String string0 = junitXmlReport0.getSkips();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSkipped("");
      String string0 = junitXmlReport0.getSkipped();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setName("com.capitalone.dashboard.model.quality.JunitXmlReport$Testcase$Failure");
      String string0 = junitXmlReport0.getName();
      assertEquals("com.capitalone.dashboard.model.quality.JunitXmlReport$Testcase$Failure", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.name = "";
      String string0 = junitXmlReport0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.hostname = "";
      junitXmlReport0.hostname = "r88K='Phc^xJM1ILwT";
      String string0 = junitXmlReport0.getHostname();
      assertEquals("r88K='Phc^xJM1ILwT", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setHostname("");
      String string0 = junitXmlReport0.getHostname();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.failures = 1611;
      int int0 = junitXmlReport0.getFailures();
      assertEquals(1611, int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setFailures((-731));
      int int0 = junitXmlReport0.getFailures();
      assertEquals((-731), int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setErrors(2913);
      int int0 = junitXmlReport0.getErrors();
      assertEquals(2913, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.errors = (-2650);
      int int0 = junitXmlReport0.getErrors();
      assertEquals((-2650), int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      // Undeclared exception!
      try { 
        junitXmlReport0.accept((QualityVisitor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.capitalone.dashboard.model.quality.JunitXmlReport", e);
      }
  }

  private void verifyException(String string, NullPointerException e) {
	// TODO Auto-generated method stub
	
}

@Test(timeout = 4000)
  public void test32()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      List<JunitXmlReport.Testcase> list0 = junitXmlReport0.getTestcase();
      List<JunitXmlReport.Testcase> list1 = junitXmlReport0.getTestcase();
      assertSame(list1, list0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setTimestamp((XMLGregorianCalendar) null);
      assertNull(junitXmlReport0.getHostname());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      String string0 = junitXmlReport0.getSystemOut();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      JunitXmlReport.Properties junitXmlReport_Properties0 = new JunitXmlReport.Properties();
      junitXmlReport0.setProperties(junitXmlReport_Properties0);
      JunitXmlReport.Properties junitXmlReport_Properties1 = junitXmlReport0.getProperties();
      assertSame(junitXmlReport_Properties1, junitXmlReport_Properties0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      String string0 = junitXmlReport0.getHostname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSkipped("-qA}]8z(#q4s^/ZnS5<");
      String string0 = junitXmlReport0.getSkipped();
      assertEquals("-qA}]8z(#q4s^/ZnS5<", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      BigDecimal bigDecimal0 = junitXmlReport0.getTime();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      int int0 = junitXmlReport0.getFailures();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      XMLGregorianCalendar xMLGregorianCalendar0 = junitXmlReport0.getTimestamp();
      assertNull(xMLGregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      JunitXmlReport.Properties junitXmlReport_Properties0 = junitXmlReport0.getProperties();
      assertNull(junitXmlReport_Properties0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      junitXmlReport0.setSystemErr("%YwC8DE/Qifu");
      String string0 = junitXmlReport0.getSystemErr();
      assertEquals("%YwC8DE/Qifu", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      int int0 = junitXmlReport0.getErrors();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      String string0 = junitXmlReport0.getSystemErr();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      String string0 = junitXmlReport0.getSkipped();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      String string0 = junitXmlReport0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      String string0 = junitXmlReport0.getSkips();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      JunitXmlReport junitXmlReport0 = new JunitXmlReport();
      int int0 = junitXmlReport0.getTests();
      assertEquals(0, int0);
  }

	/*
	 * @Test(timeout = 4000) public void test49() throws Throwable { JunitXmlReport
	 * junitXmlReport0 = new JunitXmlReport(); QualityVisitor<Object>
	 * qualityVisitor0 = (QualityVisitor<Object>) mock(QualityVisitor.class, new
	 * ViolatedAssumptionAnswer()); junitXmlReport0.accept(qualityVisitor0);
	 * assertEquals(0, junitXmlReport0.getTests()); }
	 */
  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = new JunitXmlReport.Testcase.Failure();
      junitXmlReport_Testcase0.setFailure(junitXmlReport_Testcase_Failure0);
      assertNull(junitXmlReport_Testcase0.getName());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setSkipped(":");
      assertNull(junitXmlReport_Testcase0.getName());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setClassname("");
      String string0 = junitXmlReport_Testcase0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = junitXmlReport_Testcase0.getFailure();
      assertNull(junitXmlReport_Testcase_Failure0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setError(junitXmlReport_Testcase_Error0);
      assertNull(junitXmlReport_Testcase_Error0.getMessage());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      junitXmlReport_Testcase0.setTime(bigDecimal0);
      assertNull(junitXmlReport_Testcase0.getName());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      BigDecimal bigDecimal0 = junitXmlReport_Testcase0.getTime();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      JunitXmlReport.Testcase junitXmlReport_Testcase0 = new JunitXmlReport.Testcase();
      junitXmlReport_Testcase0.setName("");
      String string0 = junitXmlReport_Testcase0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      JunitXmlReport.Properties junitXmlReport_Properties0 = new JunitXmlReport.Properties();
      List<JunitXmlReport.Properties.Property> list0 = junitXmlReport_Properties0.getProperty();
      List<JunitXmlReport.Properties.Property> list1 = junitXmlReport_Properties0.getProperty();
      assertSame(list1, list0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      JunitXmlReport.Properties.Property junitXmlReport_Properties_Property0 = new JunitXmlReport.Properties.Property();
      junitXmlReport_Properties_Property0.setValue("\"tjRZf,Gp");
      assertEquals("\"tjRZf,Gp", junitXmlReport_Properties_Property0.getValue());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      JunitXmlReport.Testcase.Failure junitXmlReport_Testcase_Failure0 = new JunitXmlReport.Testcase.Failure();
      junitXmlReport_Testcase_Failure0.setValue(";VZ");
      String string0 = junitXmlReport_Testcase_Failure0.getValue();
      assertEquals(";VZ", string0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      junitXmlReport_Testcase_Error0.setMessage(";VZ");
      assertEquals(";VZ", junitXmlReport_Testcase_Error0.getMessage());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      String string0 = junitXmlReport_Testcase_Error0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      junitXmlReport_Testcase_Error0.setValue("");
      String string0 = junitXmlReport_Testcase_Error0.getValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      JunitXmlReport.Testcase.Error junitXmlReport_Testcase_Error0 = new JunitXmlReport.Testcase.Error();
      junitXmlReport_Testcase_Error0.setType("");
      String string0 = junitXmlReport_Testcase_Error0.getMessage();
      assertNull(string0);
  }
}
