/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:49:05 GMT 2020
 */

package com.capitalone.dashboard.model.quality;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.quality.CheckstyleReport;
import com.capitalone.dashboard.model.quality.QualityVisitor;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CheckstyleReport_ESTest extends CheckstyleReport_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      QualityVisitor<String> qualityVisitor0 = (QualityVisitor<String>) mock(QualityVisitor.class, new ViolatedAssumptionAnswer());
      checkstyleReport0.accept(qualityVisitor0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      LinkedList<CheckstyleReport.CheckstyleFile> linkedList0 = new LinkedList<CheckstyleReport.CheckstyleFile>();
      CheckstyleReport.CheckstyleFile checkstyleReport_CheckstyleFile0 = new CheckstyleReport.CheckstyleFile();
      linkedList0.offer(checkstyleReport_CheckstyleFile0);
      checkstyleReport0.setFiles(linkedList0);
      List<CheckstyleReport.CheckstyleFile> list0 = checkstyleReport0.getFiles();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CheckstyleReport.CheckstyleFile checkstyleReport_CheckstyleFile0 = new CheckstyleReport.CheckstyleFile();
      List<CheckstyleReport.CheckstyleError> list0 = checkstyleReport_CheckstyleFile0.getErrors();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CheckstyleReport.CheckstyleFile checkstyleReport_CheckstyleFile0 = new CheckstyleReport.CheckstyleFile();
      LinkedList<CheckstyleReport.CheckstyleError> linkedList0 = new LinkedList<CheckstyleReport.CheckstyleError>();
      checkstyleReport_CheckstyleFile0.setErrors(linkedList0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CheckstyleReport.CheckstyleError checkstyleReport_CheckstyleError0 = new CheckstyleReport.CheckstyleError();
      checkstyleReport_CheckstyleError0.getSeverity();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CheckstyleReport.CheckstyleError checkstyleReport_CheckstyleError0 = new CheckstyleReport.CheckstyleError();
      CheckstyleReport.CheckstyleSeverity checkstyleReport_CheckstyleSeverity0 = CheckstyleReport.CheckstyleSeverity.warning;
      checkstyleReport_CheckstyleError0.setSeverity(checkstyleReport_CheckstyleSeverity0);
      assertEquals(CheckstyleReport.CheckstyleSeverity.warning, checkstyleReport_CheckstyleError0.getSeverity());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      LinkedList<CheckstyleReport.CheckstyleFile> linkedList0 = new LinkedList<CheckstyleReport.CheckstyleFile>();
      checkstyleReport0.setFiles(linkedList0);
      List<CheckstyleReport.CheckstyleFile> list0 = checkstyleReport0.getFiles();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      // Undeclared exception!
      try { 
        checkstyleReport0.accept((QualityVisitor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.capitalone.dashboard.model.quality.CheckstyleReport", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CheckstyleReport checkstyleReport0 = new CheckstyleReport();
      List<CheckstyleReport.CheckstyleFile> list0 = checkstyleReport0.getFiles();
      assertNull(list0);
  }
}
