/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 09:49:43 GMT 2020
 */

package com.capitalone.dashboard.util;

import static org.junit.Assert.fail;

import java.util.LinkedList;

import org.junit.Test;

import com.capitalone.dashboard.model.Commit;
import com.capitalone.dashboard.model.GitRequest;

public class CommitPullMatcher_ESTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Commit> linkedList0 = new LinkedList<Commit>();
      LinkedList<GitRequest> linkedList1 = new LinkedList<GitRequest>();
      // Undeclared exception!
      try { 
        CommitPullMatcher.matchCommitToPulls(linkedList0, linkedList1);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/collections/CollectionUtils
         //
         verifyException("com.capitalone.dashboard.util.CommitPullMatcher", e);
      }
  }

  private void verifyException(String string, NoClassDefFoundError e) {
	// TODO Auto-generated method stub
	
}

@Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommitPullMatcher commitPullMatcher0 = new CommitPullMatcher();
  }
}
