/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 09:48:19 GMT 2020
 */

package com.capitalone.dashboard.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.util.LinkedList;
import java.util.List;

import org.junit.Test;

public class CoreFeatureSettings_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst("faSgVCsD");
      coreFeatureSettings0.setTodoStatuses(linkedList0);
      List<String> list0 = coreFeatureSettings0.getTodoStatuses();
      assertTrue(list0.contains("faSgVCsD"));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      coreFeatureSettings0.setDoneStatuses(linkedList0);
      List<String> list0 = coreFeatureSettings0.getDoneStatuses();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerLast("com.capitalone.dashboard.util.CoreFeatureSettings");
      coreFeatureSettings0.setDoingStatuses(linkedList0);
      List<String> list0 = coreFeatureSettings0.getDoingStatuses();
      assertTrue(list0.contains("com.capitalone.dashboard.util.CoreFeatureSettings"));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      List<String> list0 = coreFeatureSettings0.getDoneStatuses();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      coreFeatureSettings0.setDoneStatuses(linkedList0);
      List<String> list0 = coreFeatureSettings0.getDoneStatuses();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      List<String> list0 = coreFeatureSettings0.getTodoStatuses();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      List<String> list0 = coreFeatureSettings0.getDoingStatuses();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      coreFeatureSettings0.setDoingStatuses(linkedList0);
      List<String> list0 = coreFeatureSettings0.getDoingStatuses();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CoreFeatureSettings coreFeatureSettings0 = new CoreFeatureSettings();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      coreFeatureSettings0.setTodoStatuses(linkedList0);
      List<String> list0 = coreFeatureSettings0.getTodoStatuses();
      assertEquals(0, list0.size());
  }
}
