/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 09:47:05 GMT 2020
 */

package com.capitalone.dashboard.util;

import org.junit.Test;

public class EncryptionException_ESTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EncryptionException encryptionException0 = new EncryptionException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EncryptionException encryptionException0 = new EncryptionException("'~?FtPFO}Ed&IS");
  }
}
