/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 09:48:34 GMT 2020
 */

package com.capitalone.dashboard.util;

import org.junit.Test;

public class FeatureFlagsEnum_ESTest  {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
