/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 09:45:35 GMT 2020
 */

package com.capitalone.dashboard.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.regex.PatternSyntaxException;

import org.junit.Test;

public class GitBranchSpec_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec(" ");
      String string0 = gitBranchSpec0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec(":2?c![*6{?{BZ");
      // Undeclared exception!
      try { 
        gitBranchSpec0.matches(":2?c![*6{?{BZ");
        fail("Expecting exception: PatternSyntaxException");
      
      } catch(PatternSyntaxException e) {
         //
         // Unclosed character class near index 11\r
         // 2?c![*6{?{BZ\r
         //            ^
         //
         verifyException("java.util.regex.Pattern", e);
      }
  }

  private void verifyException(String string, PatternSyntaxException e) {
	// TODO Auto-generated method stub
	
}

@Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec(" ");
      // Undeclared exception!
      try { 
        gitBranchSpec0.matches(" ");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec(" :");
      // Undeclared exception!
      try { 
        gitBranchSpec0.matches((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec("[:/*");
      boolean boolean0 = gitBranchSpec0.matches("[:/*");
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec("+*e]vN4i&Gj[");
      boolean boolean0 = gitBranchSpec0.matches("+*e]vN4i&Gj[");
      assertTrue(boolean0);
      assertEquals("+*e]vN4i&Gj[", gitBranchSpec0.toString());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec("");
      assertEquals("**", gitBranchSpec0.toString());
      
      boolean boolean0 = gitBranchSpec0.matches("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = null;
      try {
        gitBranchSpec0 = new GitBranchSpec((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.capitalone.dashboard.util.GitBranchSpec", e);
      }
  }

  private void verifyException(String string, IllegalArgumentException e) {
	// TODO Auto-generated method stub
	
}

@Test(timeout = 4000)
  public void test8()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec("+*e]vN4i&Gj[");
      String string0 = gitBranchSpec0.toString();
      assertEquals("+*e]vN4i&Gj[", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      GitBranchSpec gitBranchSpec0 = new GitBranchSpec(":m");
      String string0 = gitBranchSpec0.getName();
      assertEquals(":m", string0);
  }
}
