/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:43:51 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.ApiToken;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ApiToken_ESTest extends ApiToken_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = ApiToken.hash("sha512:");
      assertEquals("sha512:", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken("k)z", "sha512:", (Long) null);
      apiToken0.getExpirationDt();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken("k)z", "sha512:", (Long) null);
      Long long0 = new Long(0L);
      apiToken0.setExpirationDt(long0);
      apiToken0.getExpirationDt();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long((-21L));
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", long0);
      apiToken0.getExpirationDt();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Long long0 = new Long((-355L));
      ApiToken apiToken0 = new ApiToken((String) null, "sha512:SdvvC(\"", long0);
      apiToken0.getApiUser();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Long long0 = new Long((-6032L));
      ApiToken apiToken0 = new ApiToken("", "sha512:", long0);
      apiToken0.getApiUser();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Long long0 = new Long(1L);
      ApiToken apiToken0 = new ApiToken("sha512:?M/i3${1EP]*EVD", "sha512:", long0);
      apiToken0.checkApiKey("sha512:OTD)Arj");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", (Long) null);
      // Undeclared exception!
      try { 
        apiToken0.setApiKey((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Long long0 = new Long(1L);
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", long0);
      // Undeclared exception!
      try { 
        apiToken0.setApiKey("SdvvC(\"WZF[+mCe");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.ApiToken", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        ApiToken.hash((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        ApiToken.hash("sha412:");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.ApiToken", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken("sha512:SdvvC(\"WZF[+mCe", "sha512:SdvvC(\"WZF[+mCe", (Long) null);
      // Undeclared exception!
      try { 
        apiToken0.checkApiKey((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Long long0 = new Long((-936L));
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", long0);
      // Undeclared exception!
      try { 
        apiToken0.checkApiKey("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.ApiToken", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Long long0 = new Long(0L);
      ApiToken apiToken0 = null;
      try {
        apiToken0 = new ApiToken("", (String) null, long0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Long long0 = new Long((-989L));
      ApiToken apiToken0 = null;
      try {
        apiToken0 = new ApiToken("", "1E", long0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.ApiToken", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken(",>]1GIc]^V", "sha512:", (Long) null);
      apiToken0.setApiUser("sha512:");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Long long0 = new Long(1L);
      ApiToken apiToken0 = new ApiToken("sha512:ApiToken [apiUser=sha512:, apiKey=sha512:]", "sha512:ApiToken [apiUser=sha512:, apiKey=sha512:]", long0);
      apiToken0.getExpirationDt();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken("sha512:SdvvC(\"WZF[+mCe", "sha512:SdvvC(\"WZF[+mCe", (Long) null);
      apiToken0.setApiKey("sha512:SdvvC(\"WZF[+mCe");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Long long0 = new Long((-946L));
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", long0);
      apiToken0.getApiUser();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken(",>]1GIc]^V", "sha512:", (Long) null);
      apiToken0.checkApiKey("sha512:");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Long long0 = new Long((-946L));
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", long0);
      apiToken0.isHashed();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Long long0 = new Long((-946L));
      ApiToken apiToken0 = new ApiToken("sha512:", "sha512:", long0);
      apiToken0.getApiKey();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ApiToken apiToken0 = new ApiToken(",>]1GIc]^V", "sha512:", (Long) null);
      apiToken0.toString();
  }
}
