/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:30:22 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.AuditType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuditType_ESTest extends AuditType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuditType auditType0 = AuditType.fromString("perf_test");
      assertEquals(AuditType.PERF_TEST, auditType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AuditType[] auditTypeArray0 = AuditType.values();
      assertEquals(10, auditTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AuditType auditType0 = AuditType.valueOf("ALL");
      assertEquals(AuditType.ALL, auditType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        AuditType.fromString("9XP4<Q]'W");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 9XP4<Q]'W is not a Audit Type
         //
         verifyException("com.capitalone.dashboard.model.AuditType", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AuditType auditType0 = AuditType.fromString("TEST_RESULT");
      assertEquals(AuditType.TEST_RESULT, auditType0);
  }
}
