/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:27:15 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.Authentication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Authentication_ESTest extends Authentication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = Authentication.hash("sha512:Authentication [username=");
      assertEquals("sha512:Authentication [username=", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:sha512:", "sha512:sha512:");
      authentication0.setUsername((String) null);
      authentication0.getUsername();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Authentication authentication0 = new Authentication("", "sha512:sha512W?:");
      authentication0.getUsername();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:sha512:", "sha512:sha512:");
      authentication0.checkPassword("sha512:");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      // Undeclared exception!
      try { 
        authentication0.setPassword((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      // Undeclared exception!
      try { 
        authentication0.setPassword("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.Authentication", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        Authentication.hash((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        Authentication.hash("sha5129");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.Authentication", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Authentication authentication0 = new Authentication((String) null, "sha512:");
      // Undeclared exception!
      try { 
        authentication0.checkPassword((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:TcPXe19])1V[cC\"}MSU", "sha512:TcPXe19])1V[cC\"}MSU");
      // Undeclared exception!
      try { 
        authentication0.checkPassword("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.Authentication", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Authentication authentication0 = null;
      try {
        authentication0 = new Authentication((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      authentication0.getPassword();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      authentication0.isHashed();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      authentication0.toString();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      authentication0.checkPassword("sha512:");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      authentication0.setPassword("sha512:");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Authentication authentication0 = new Authentication("sha512:", "sha512:");
      authentication0.getUsername();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Authentication authentication0 = null;
      try {
        authentication0 = new Authentication(",b%BN^iba@de~9A7iE", ",b%BN^iba@de~9A7iE");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/hash/Hashing
         //
         verifyException("com.capitalone.dashboard.model.Authentication", e);
      }
  }
}
