/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:01:53 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.CommitStatus;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommitStatus_ESTest extends CommitStatus_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setState("?mGSd]S^&O>x~>m0");
      String string0 = commitStatus0.getState();
      assertEquals("?mGSd]S^&O>x~>m0", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setState("");
      String string0 = commitStatus0.getState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setDescription("AcA1gmY[Svy3+V)G");
      String string0 = commitStatus0.getDescription();
      assertEquals("AcA1gmY[Svy3+V)G", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setContext("AcA1gmY[Svy3+V)G");
      String string0 = commitStatus0.getContext();
      assertEquals("AcA1gmY[Svy3+V)G", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setContext("");
      String string0 = commitStatus0.getContext();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setAuthorLDAPDN("9d;rv-");
      String string0 = commitStatus0.getAuthorLDAPDN();
      assertEquals("9d;rv-", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setAuthor("");
      String string0 = commitStatus0.getAuthor();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setDescription("");
      String string0 = commitStatus0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      String string0 = commitStatus0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      String string0 = commitStatus0.getState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      String string0 = commitStatus0.getContext();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setAuthor("?mGSd]S^&O>x~>m0");
      String string0 = commitStatus0.getAuthor();
      assertEquals("?mGSd]S^&O>x~>m0", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      String string0 = commitStatus0.getAuthor();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      commitStatus0.setAuthorLDAPDN("");
      String string0 = commitStatus0.getAuthorLDAPDN();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommitStatus commitStatus0 = new CommitStatus();
      String string0 = commitStatus0.getAuthorLDAPDN();
      assertNull(string0);
  }
}
