/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:42:32 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.CommitType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommitType_ESTest extends CommitType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommitType commitType0 = CommitType.fromString("NotBuilt");
      assertEquals(CommitType.NotBuilt, commitType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommitType[] commitTypeArray0 = CommitType.values();
      assertEquals(3, commitTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CommitType commitType0 = CommitType.valueOf("NotBuilt");
      assertEquals(CommitType.NotBuilt, commitType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommitType.fromString("notbuilu");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // notbuilu is not a valid Commit Type
         //
         verifyException("com.capitalone.dashboard.model.CommitType", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CommitType commitType0 = CommitType.fromString("New");
      assertEquals(CommitType.New, commitType0);
  }
}
