/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:20:17 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.DashboardType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DashboardType_ESTest extends DashboardType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DashboardType dashboardType0 = DashboardType.fromString("Team");
      assertEquals(DashboardType.Team, dashboardType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DashboardType[] dashboardTypeArray0 = DashboardType.values();
      assertEquals(2, dashboardTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DashboardType dashboardType0 = DashboardType.valueOf("Product");
      assertEquals(DashboardType.Product, dashboardType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        DashboardType.fromString("seam");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // seam is not a valid DashboardType
         //
         verifyException("com.capitalone.dashboard.model.DashboardType", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DashboardType dashboardType0 = DashboardType.fromString("Product");
      assertEquals(DashboardType.Product, dashboardType0);
  }
}
