/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:58:26 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.FeatureHistory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FeatureHistory_ESTest extends FeatureHistory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsToDo("rK!");
      featureHistory0.getsToDo();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsStatus("aOK6GTmeKX>!c+");
      featureHistory0.getsStatus();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsStatus("");
      featureHistory0.getsStatus();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsSoftwareTesting("#");
      featureHistory0.getsSoftwareTesting();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsSoftwareTesting("");
      featureHistory0.getsSoftwareTesting();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsEstimate("pnI;+)NyM(hc=h");
      featureHistory0.getsEstimate();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsAssetState("(F|VhjraVOWAkXKD");
      featureHistory0.getsAssetState();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsAssetState("");
      featureHistory0.getsAssetState();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setTeamID("+");
      featureHistory0.getTeamID();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setStoryID("com.capitalone.dashboard.model.BaseModel");
      featureHistory0.getStoryID();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setSprintID("^&,,$jna@?91");
      featureHistory0.getSprintID();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setSprintEndDate("bJIQrMVl|");
      featureHistory0.getSprintEndDate();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setSprintEndDate("");
      featureHistory0.getSprintEndDate();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setSprintBeginDate("^tC>nJ%'c_3f*");
      featureHistory0.getSprintBeginDate();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setSprintBeginDate("");
      featureHistory0.getSprintBeginDate();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setReportedDate("com.capitalone.dashboard.model.FeatureHistory");
      featureHistory0.getReportedDate();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setProjectID("XhYTYV");
      featureHistory0.getProjectID();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setIsDeleted("com.capitalone.dashboard.model.FeatureHistory");
      featureHistory0.getIsDeleted();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setChangeDate("Z1z0D|%T],.TPC~Q`v");
      featureHistory0.getChangeDate();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setStoryID("");
      featureHistory0.getStoryID();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setReportedDate("");
      featureHistory0.getReportedDate();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getSprintBeginDate();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getProjectID();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getSprintEndDate();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsEstimate("");
      featureHistory0.getsEstimate();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getIsDeleted();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getStoryID();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getsToDo();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setTeamID("");
      featureHistory0.getTeamID();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setProjectID("");
      featureHistory0.getProjectID();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getSprintID();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setIsDeleted("");
      featureHistory0.getIsDeleted();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getsAssetState();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setSprintID("");
      featureHistory0.getSprintID();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setsToDo("");
      featureHistory0.getsToDo();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getsStatus();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.setChangeDate("");
      featureHistory0.getChangeDate();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getsEstimate();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getChangeDate();
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getsSoftwareTesting();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getReportedDate();
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      FeatureHistory featureHistory0 = new FeatureHistory();
      featureHistory0.getTeamID();
  }
}
