/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:55:20 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.GitHubPaging;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GitHubPaging_ESTest extends GitHubPaging_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setLastPage(true);
      boolean boolean0 = gitHubPaging0.isLastPage();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setTotalCount(1661);
      int int0 = gitHubPaging0.getTotalCount();
      assertEquals(1661, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setTotalCount((-1));
      int int0 = gitHubPaging0.getTotalCount();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setCursor("Gb'CS\"2>\"eX,['uZW");
      String string0 = gitHubPaging0.getCursor();
      assertEquals("Gb'CS\"2>\"eX,['uZW", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setCurrentCount(1087);
      int int0 = gitHubPaging0.getCurrentCount();
      assertEquals(1087, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setCurrentCount((-1));
      int int0 = gitHubPaging0.getCurrentCount();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      int int0 = gitHubPaging0.getCurrentCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      String string0 = gitHubPaging0.getCursor();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      int int0 = gitHubPaging0.getTotalCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      gitHubPaging0.setCursor("");
      String string0 = gitHubPaging0.getCursor();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GitHubPaging gitHubPaging0 = new GitHubPaging();
      boolean boolean0 = gitHubPaging0.isLastPage();
      assertFalse(boolean0);
  }
}
