/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:53:45 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.KeyValueLog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KeyValueLog_ESTest extends KeyValueLog_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KeyValueLog keyValueLog0 = new KeyValueLog();
      KeyValueLog keyValueLog1 = keyValueLog0.with("", (Object) null);
      keyValueLog1.toString();
      Object object0 = new Object();
      keyValueLog0.with("", (Object) null);
      KeyValueLog keyValueLog2 = keyValueLog1.with("", object0);
      KeyValueLog keyValueLog3 = keyValueLog2.with("", "");
      Object object1 = new Object();
      keyValueLog0.toString();
      KeyValueLog keyValueLog4 = keyValueLog2.with("", object1);
      keyValueLog4.toString();
      Object object2 = new Object();
      keyValueLog4.with("", object2);
      keyValueLog1.toString();
      keyValueLog0.toString();
      keyValueLog0.toString();
      Object object3 = new Object();
      KeyValueLog keyValueLog5 = keyValueLog2.with("=\"null\" =\"null\" =\"null\" =\"java.lang.Object@26c81124\" =\"\" =\"\"", object3);
      Object object4 = new Object();
      KeyValueLog keyValueLog6 = keyValueLog5.with((String) null, object4);
      keyValueLog5.toString();
      keyValueLog0.toString();
      KeyValueLog keyValueLog7 = keyValueLog6.with("fdTU,_i9VXq6R", "=\"null\" =\"null\"");
      keyValueLog6.toString();
      KeyValueLog keyValueLog8 = keyValueLog7.with("=\"null\" =\"null\" =\"null\" =\"java.lang.Object@26c81124\" =\"\" =\"\" =\"java.lang.Object@6cffed64\" =\"java.lang.Object@6cffed64\" =\"java.lang.Object@19ae5d2a\" =\"java.lang.Object@19ae5d2a\" =\"java.lang.Object@19ae5d2a\" =\"java.lang.Object@19ae5d2a\"", keyValueLog3);
      keyValueLog8.toString();
      String string0 = "";
      KeyValueLog keyValueLog9 = keyValueLog2.with(string0, string0);
      keyValueLog9.toString();
      keyValueLog7.toString();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KeyValueLog keyValueLog0 = new KeyValueLog();
      KeyValueLog keyValueLog1 = keyValueLog0.with("", "");
      KeyValueLog keyValueLog2 = keyValueLog1.with("", "");
      keyValueLog0.toString();
      keyValueLog2.toString();
      String string0 = keyValueLog2.toString();
      //  // Unstable assertion: assertEquals("=\"\" =\"\" =\"\" =\"\" =\"\"", string0);
  }
}
