/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:40:46 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.LibraryPolicyThreatDisposition;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LibraryPolicyThreatDisposition_ESTest extends LibraryPolicyThreatDisposition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LibraryPolicyThreatDisposition[] libraryPolicyThreatDispositionArray0 = LibraryPolicyThreatDisposition.values();
      assertEquals(8, libraryPolicyThreatDispositionArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LibraryPolicyThreatDisposition libraryPolicyThreatDisposition0 = LibraryPolicyThreatDisposition.valueOf("NotUsed");
      assertEquals(LibraryPolicyThreatDisposition.NotUsed, libraryPolicyThreatDisposition0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LibraryPolicyThreatDisposition libraryPolicyThreatDisposition0 = LibraryPolicyThreatDisposition.fromString("");
      assertEquals(LibraryPolicyThreatDisposition.Unknown, libraryPolicyThreatDisposition0);
  }
}
