/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:30:59 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.NameValue;
import com.capitalone.dashboard.model.NameValueCount;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NameValueCount_ESTest extends NameValueCount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NameValueCount nameValueCount0 = new NameValueCount((NameValue) null, (-498));
      nameValueCount0.getKeyValue();
      assertEquals((-498), nameValueCount0.getCount());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NameValueCount nameValueCount0 = new NameValueCount((NameValue) null, (-498));
      nameValueCount0.setCount(0);
      int int0 = nameValueCount0.getCount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NameValue nameValue0 = new NameValue();
      NameValueCount nameValueCount0 = new NameValueCount(nameValue0, (-2693));
      nameValueCount0.setCount(2021);
      int int0 = nameValueCount0.getCount();
      assertEquals(2021, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NameValue nameValue0 = new NameValue();
      NameValueCount nameValueCount0 = new NameValueCount(nameValue0, (-2693));
      nameValueCount0.setKeyValue(nameValue0);
      assertEquals((-2693), nameValueCount0.getCount());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NameValue nameValue0 = new NameValue();
      NameValueCount nameValueCount0 = new NameValueCount(nameValue0, (-2693));
      int int0 = nameValueCount0.getCount();
      assertEquals((-2693), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NameValue nameValue0 = new NameValue();
      NameValueCount nameValueCount0 = new NameValueCount(nameValue0, (-2693));
      nameValueCount0.getKeyValue();
      assertEquals((-2693), nameValueCount0.getCount());
  }
}
