/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:20:26 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.PerformanceMetric;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PerformanceMetric_ESTest extends PerformanceMetric_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PerformanceMetric performanceMetric0 = new PerformanceMetric();
      performanceMetric0.setValue("X.[1");
      Object object0 = performanceMetric0.getValue();
      assertEquals("X.[1", object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PerformanceMetric performanceMetric0 = new PerformanceMetric();
      performanceMetric0.setName("X.[1");
      String string0 = performanceMetric0.getName();
      assertEquals("X.[1", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PerformanceMetric performanceMetric0 = new PerformanceMetric();
      performanceMetric0.setName("");
      String string0 = performanceMetric0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PerformanceMetric performanceMetric0 = new PerformanceMetric();
      Object object0 = performanceMetric0.getValue();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PerformanceMetric performanceMetric0 = new PerformanceMetric();
      String string0 = performanceMetric0.getName();
      assertNull(string0);
  }
}
