/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:39:33 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.Review;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Review_ESTest extends Review_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Review review0 = new Review();
      review0.setUpdatedAt(2100L);
      long long0 = review0.getUpdatedAt();
      assertEquals(2100L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Review review0 = new Review();
      review0.setState("tSu$$k,^}W2\"");
      String string0 = review0.getState();
      assertEquals("tSu$$k,^}W2\"", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Review review0 = new Review();
      review0.setState("");
      String string0 = review0.getState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Review review0 = new Review();
      review0.setCreatedAt(1304L);
      long long0 = review0.getCreatedAt();
      assertEquals(1304L, long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Review review0 = new Review();
      review0.setBody("|C3:Rgd");
      String string0 = review0.getBody();
      assertEquals("|C3:Rgd", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Review review0 = new Review();
      review0.setAuthorLDAPDN("!Qy4\"H2D~U");
      String string0 = review0.getAuthorLDAPDN();
      assertEquals("!Qy4\"H2D~U", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Review review0 = new Review();
      review0.setAuthorLDAPDN("");
      String string0 = review0.getAuthorLDAPDN();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Review review0 = new Review();
      review0.setAuthor("uV\"~E>]-%p[G9");
      String string0 = review0.getAuthor();
      assertEquals("uV\"~E>]-%p[G9", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Review review0 = new Review();
      String string0 = review0.getAuthor();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Review review0 = new Review();
      long long0 = review0.getCreatedAt();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Review review0 = new Review();
      String string0 = review0.getState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Review review0 = new Review();
      review0.setBody("");
      String string0 = review0.getBody();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Review review0 = new Review();
      String string0 = review0.getAuthorLDAPDN();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Review review0 = new Review();
      long long0 = review0.getUpdatedAt();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Review review0 = new Review();
      String string0 = review0.getBody();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Review review0 = new Review();
      review0.setAuthor("");
      String string0 = review0.getAuthor();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Review review0 = new Review();
      review0.setCreatedAt((-1L));
      long long0 = review0.getCreatedAt();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Review review0 = new Review();
      review0.setUpdatedAt((-1L));
      long long0 = review0.getUpdatedAt();
      assertEquals((-1L), long0);
  }
}
