/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:16:12 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.model.ScoreDisplayType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScoreDisplayType_ESTest extends ScoreDisplayType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScoreDisplayType scoreDisplayType0 = ScoreDisplayType.fromString("WIDGET");
      assertEquals(ScoreDisplayType.WIDGET, scoreDisplayType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScoreDisplayType[] scoreDisplayTypeArray0 = ScoreDisplayType.values();
      assertEquals(2, scoreDisplayTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ScoreDisplayType scoreDisplayType0 = ScoreDisplayType.valueOf("HEADER");
      assertEquals(ScoreDisplayType.HEADER, scoreDisplayType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ScoreDisplayType scoreDisplayType0 = ScoreDisplayType.fromString("header");
      assertEquals(ScoreDisplayType.HEADER, scoreDisplayType0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ScoreDisplayType scoreDisplayType0 = ScoreDisplayType.fromString("HDADER");
      assertEquals(ScoreDisplayType.HEADER, scoreDisplayType0);
  }
}
