/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 14:55:04 GMT 2020
 */

package com.capitalone.dashboard.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.TestSuiteType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestSuiteType_ESTest extends TestSuiteType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestSuiteType testSuiteType0 = TestSuiteType.fromString("Integration");
      assertEquals(TestSuiteType.Integration, testSuiteType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestSuiteType[] testSuiteTypeArray0 = TestSuiteType.values();
      assertEquals(7, testSuiteTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TestSuiteType testSuiteType0 = TestSuiteType.valueOf("Integration");
      assertEquals(TestSuiteType.Integration, testSuiteType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TestSuiteType testSuiteType0 = TestSuiteType.fromString("unit");
      assertEquals(TestSuiteType.Unit, testSuiteType0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        TestSuiteType.fromString("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         //  is not a valid TestSuiteType.
         //
         verifyException("com.capitalone.dashboard.model.TestSuiteType", e);
      }
  }
}
