/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:09:30 GMT 2020
 */

package com.capitalone.dashboard.request;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.request.CloudInstanceListRefreshRequest;
import java.util.Collection;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CloudInstanceListRefreshRequest_ESTest extends CloudInstanceListRefreshRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      MockDate mockDate0 = new MockDate(1685L);
      cloudInstanceListRefreshRequest0.setRefreshDate(mockDate0);
      Date date0 = cloudInstanceListRefreshRequest0.getRefreshDate();
      assertEquals("Thu Jan 01 00:00:01 GMT 1970", date0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      LinkedList<Locale.LanguageRange> linkedList0 = new LinkedList<Locale.LanguageRange>();
      Locale locale0 = Locale.CANADA_FRENCH;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) linkedList0, (Collection<String>) set0);
      cloudInstanceListRefreshRequest0.setInstanceIds(list0);
      List<String> list1 = cloudInstanceListRefreshRequest0.getInstanceIds();
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      cloudInstanceListRefreshRequest0.setAccountNumber("com.capitalone.dashboard.request.CloudInstanceListRefreshRequest");
      String string0 = cloudInstanceListRefreshRequest0.getAccountNumber();
      assertEquals("com.capitalone.dashboard.request.CloudInstanceListRefreshRequest", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      cloudInstanceListRefreshRequest0.setAccountNumber("");
      String string0 = cloudInstanceListRefreshRequest0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      cloudInstanceListRefreshRequest0.setInstanceIds(linkedList0);
      linkedList0.add("");
      List<String> list0 = cloudInstanceListRefreshRequest0.getInstanceIds();
      assertTrue(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      List<String> list0 = cloudInstanceListRefreshRequest0.getInstanceIds();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      Date date0 = cloudInstanceListRefreshRequest0.getRefreshDate();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CloudInstanceListRefreshRequest cloudInstanceListRefreshRequest0 = new CloudInstanceListRefreshRequest();
      String string0 = cloudInstanceListRefreshRequest0.getAccountNumber();
      assertNull(string0);
  }
}
