/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:06:53 GMT 2020
 */

package com.capitalone.dashboard.request;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.NameValue;
import com.capitalone.dashboard.request.CloudInstanceCreateRequest;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CloudInstanceCreateRequest_ESTest extends CloudInstanceCreateRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceId("zV=Y3k,@h<Z");
      cloudInstanceCreateRequest0.setAccountNumber("zV=Y3k,@h<Z");
      cloudInstanceCreateRequest0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceId("");
      // Undeclared exception!
      try { 
        cloudInstanceCreateRequest0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.capitalone.dashboard.request.CloudInstanceCreateRequest", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setVirtualNetworkId("com.capitalone.dashboard.model.NameValue");
      String string0 = cloudInstanceCreateRequest0.getVirtualNetworkId();
      assertEquals("com.capitalone.dashboard.model.NameValue", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setVirtualNetworkId("");
      String string0 = cloudInstanceCreateRequest0.getVirtualNetworkId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setTags((List<NameValue>) null);
      List<NameValue> list0 = cloudInstanceCreateRequest0.getTags();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      LinkedList<NameValue> linkedList0 = new LinkedList<NameValue>();
      NameValue nameValue0 = new NameValue("com.capitalone.dashboard.model.NameValue", "");
      linkedList0.add(nameValue0);
      cloudInstanceCreateRequest0.setTags(linkedList0);
      List<NameValue> list0 = cloudInstanceCreateRequest0.getTags();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setSubnetId("Y)4N`-&7cSWxN");
      String string0 = cloudInstanceCreateRequest0.getSubnetId();
      assertEquals("Y)4N`-&7cSWxN", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setSubnetId("");
      String string0 = cloudInstanceCreateRequest0.getSubnetId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setStatus("com.capitalone.dashboard.request.CloudInstanceCreateRequest");
      String string0 = cloudInstanceCreateRequest0.getStatus();
      assertEquals("com.capitalone.dashboard.request.CloudInstanceCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setStatus("");
      String string0 = cloudInstanceCreateRequest0.getStatus();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      cloudInstanceCreateRequest0.setSecurityGroups(linkedList0);
      List<String> list0 = cloudInstanceCreateRequest0.getSecurityGroups();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setRootDeviceName("com.capitalone.dashboard.model.NameValue");
      String string0 = cloudInstanceCreateRequest0.getRootDeviceName();
      assertEquals("com.capitalone.dashboard.model.NameValue", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setRootDeviceName("");
      String string0 = cloudInstanceCreateRequest0.getRootDeviceName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPublicIp("qV&qq\"m,o");
      String string0 = cloudInstanceCreateRequest0.getPublicIp();
      assertEquals("qV&qq\"m,o", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPublicIp("");
      String string0 = cloudInstanceCreateRequest0.getPublicIp();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPublicDns("=A``u?A");
      String string0 = cloudInstanceCreateRequest0.getPublicDns();
      assertEquals("=A``u?A", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPublicDns("");
      String string0 = cloudInstanceCreateRequest0.getPublicDns();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPrivateIp("p2W!@ IGl>Nw");
      String string0 = cloudInstanceCreateRequest0.getPrivateIp();
      assertEquals("p2W!@ IGl>Nw", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPrivateIp("");
      String string0 = cloudInstanceCreateRequest0.getPrivateIp();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPrivateDns("com.capitalone.dashboard.request.CloudInstanceCreateRequest");
      String string0 = cloudInstanceCreateRequest0.getPrivateDns();
      assertEquals("com.capitalone.dashboard.request.CloudInstanceCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setPrivateDns("");
      String string0 = cloudInstanceCreateRequest0.getPrivateDns();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setNetworkOut("z");
      String string0 = cloudInstanceCreateRequest0.getNetworkOut();
      assertEquals("z", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setNetworkOut("");
      String string0 = cloudInstanceCreateRequest0.getNetworkOut();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setNetworkIn("com.capitalone.dashboard.model.NameValue");
      String string0 = cloudInstanceCreateRequest0.getNetworkIn();
      assertEquals("com.capitalone.dashboard.model.NameValue", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setNetworkIn("");
      String string0 = cloudInstanceCreateRequest0.getNetworkIn();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setLastUpdatedDate("0BVp&H(x|;>W[z_");
      String string0 = cloudInstanceCreateRequest0.getLastUpdatedDate();
      assertEquals("0BVp&H(x|;>W[z_", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setLastUpdatedDate("");
      String string0 = cloudInstanceCreateRequest0.getLastUpdatedDate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setLastAction("com.capitalone.dashboard.request.CloudInstanceCreateRequest");
      String string0 = cloudInstanceCreateRequest0.getLastAction();
      assertEquals("com.capitalone.dashboard.request.CloudInstanceCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setLastAction("");
      String string0 = cloudInstanceCreateRequest0.getLastAction();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsTagged("");
      String string0 = cloudInstanceCreateRequest0.getIsTagged();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsStopped("j?_F W:Y");
      String string0 = cloudInstanceCreateRequest0.getIsStopped();
      assertEquals("j?_F W:Y", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsStopped("");
      String string0 = cloudInstanceCreateRequest0.getIsStopped();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsMonitored(".PY[V2");
      String string0 = cloudInstanceCreateRequest0.getIsMonitored();
      assertEquals(".PY[V2", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsMonitored("");
      String string0 = cloudInstanceCreateRequest0.getIsMonitored();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsEncrypted("zF&;UdE_k");
      String string0 = cloudInstanceCreateRequest0.getIsEncrypted();
      assertEquals("zF&;UdE_k", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsEncrypted("");
      String string0 = cloudInstanceCreateRequest0.getIsEncrypted();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceType("s3Z\";E,d2E=%<5s");
      String string0 = cloudInstanceCreateRequest0.getInstanceType();
      assertEquals("s3Z\";E,d2E=%<5s", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceType("");
      String string0 = cloudInstanceCreateRequest0.getInstanceType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceOwner("IvSG");
      String string0 = cloudInstanceCreateRequest0.getInstanceOwner();
      assertEquals("IvSG", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceOwner("");
      String string0 = cloudInstanceCreateRequest0.getInstanceOwner();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceId("^<:/]l`<ME");
      String string0 = cloudInstanceCreateRequest0.getInstanceId();
      assertEquals("^<:/]l`<ME", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setImageId("Nj$oR;XT+]8x3(/v");
      String string0 = cloudInstanceCreateRequest0.getImageId();
      assertEquals("Nj$oR;XT+]8x3(/v", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setImageId("");
      String string0 = cloudInstanceCreateRequest0.getImageId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setImageExpirationDate("m{dEjoPe");
      String string0 = cloudInstanceCreateRequest0.getImageExpirationDate();
      assertEquals("m{dEjoPe", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setImageApproved("");
      String string0 = cloudInstanceCreateRequest0.getImageApproved();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setDiskWrite("$OW");
      String string0 = cloudInstanceCreateRequest0.getDiskWrite();
      assertEquals("$OW", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setDiskWrite("");
      String string0 = cloudInstanceCreateRequest0.getDiskWrite();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setDiskRead("oA|0:9[\u0006S\"$at{");
      String string0 = cloudInstanceCreateRequest0.getDiskRead();
      assertEquals("oA|0:9[\u0006S\"$at{", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setDiskRead("");
      String string0 = cloudInstanceCreateRequest0.getDiskRead();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setCpuUtilization("");
      String string0 = cloudInstanceCreateRequest0.getCpuUtilization();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setAutoScaleName("com.capitalone.dashboard.model.NameValue");
      String string0 = cloudInstanceCreateRequest0.getAutoScaleName();
      assertEquals("com.capitalone.dashboard.model.NameValue", string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setAutoScaleName("");
      String string0 = cloudInstanceCreateRequest0.getAutoScaleName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setAge("*XHl");
      String string0 = cloudInstanceCreateRequest0.getAge();
      assertEquals("*XHl", string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setAge("");
      String string0 = cloudInstanceCreateRequest0.getAge();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setAccountNumber("x~wZ m\"#oDAW5CEXf");
      String string0 = cloudInstanceCreateRequest0.getAccountNumber();
      assertEquals("x~wZ m\"#oDAW5CEXf", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setAccountNumber("");
      String string0 = cloudInstanceCreateRequest0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceId("4{nT$?F;!YE+]}%c");
      CloudInstanceCreateRequest cloudInstanceCreateRequest1 = new CloudInstanceCreateRequest();
      boolean boolean0 = cloudInstanceCreateRequest0.equals(cloudInstanceCreateRequest1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceId("4{nT$?F;!YE+]}%c");
      CloudInstanceCreateRequest cloudInstanceCreateRequest1 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest1.setInstanceId("4{nT$?F;!YE+]}%c");
      // Undeclared exception!
      try { 
        cloudInstanceCreateRequest0.equals(cloudInstanceCreateRequest1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      boolean boolean0 = cloudInstanceCreateRequest0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      boolean boolean0 = cloudInstanceCreateRequest0.equals(cloudInstanceCreateRequest0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      boolean boolean0 = cloudInstanceCreateRequest0.equals("4{nT$?F;!YE+]}%c");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setCpuUtilization("EZ4{nT$?F;!YE+]}%c");
      String string0 = cloudInstanceCreateRequest0.getCpuUtilization();
      assertEquals("EZ4{nT$?F;!YE+]}%c", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setImageApproved("kq`D2Pr*tbkZ76QG@$");
      String string0 = cloudInstanceCreateRequest0.getImageApproved();
      assertEquals("kq`D2Pr*tbkZ76QG@$", string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getInstanceId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getPrivateIp();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getPrivateDns();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getLastUpdatedDate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getInstanceOwner();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getImageId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getIsStopped();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setImageExpirationDate("");
      String string0 = cloudInstanceCreateRequest0.getImageExpirationDate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getSubnetId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getImageApproved();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getIsMonitored();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getCpuUtilization();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getStatus();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getAutoScaleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setSecurityGroups((List<String>) null);
      List<String> list0 = cloudInstanceCreateRequest0.getSecurityGroups();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      List<String> list0 = cloudInstanceCreateRequest0.getSecurityGroups();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      List<NameValue> list0 = cloudInstanceCreateRequest0.getTags();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setInstanceId("");
      String string0 = cloudInstanceCreateRequest0.getInstanceId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getRootDeviceName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getDiskRead();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getNetworkIn();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getDiskWrite();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getLastAction();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getPublicIp();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getVirtualNetworkId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getAge();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getIsTagged();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getPublicDns();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      cloudInstanceCreateRequest0.setIsTagged("P<u(YgS?P");
      String string0 = cloudInstanceCreateRequest0.getIsTagged();
      assertEquals("P<u(YgS?P", string0);
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getNetworkOut();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getIsEncrypted();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getInstanceType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      CloudInstanceCreateRequest cloudInstanceCreateRequest0 = new CloudInstanceCreateRequest();
      String string0 = cloudInstanceCreateRequest0.getImageExpirationDate();
      assertNull(string0);
  }
}
