/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:13:42 GMT 2020
 */

package com.capitalone.dashboard.request;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.capitalone.dashboard.model.NameValue;
import com.capitalone.dashboard.request.CloudSubnetCreateRequest;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CloudSubnetCreateRequest_ESTest extends CloudSubnetCreateRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setAccountNumber("DWshr");
      cloudSubnetCreateRequest0.setSubnetId("DWshr");
      cloudSubnetCreateRequest0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubnetId("DWshr");
      // Undeclared exception!
      try { 
        cloudSubnetCreateRequest0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.capitalone.dashboard.request.CloudSubnetCreateRequest", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setZone("v]q--l @wrnq");
      String string0 = cloudSubnetCreateRequest0.getZone();
      assertEquals("v]q--l @wrnq", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setZone("");
      String string0 = cloudSubnetCreateRequest0.getZone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setVirtualNetworkId("Ykbbp.'0pEs");
      String string0 = cloudSubnetCreateRequest0.getVirtualNetworkId();
      assertEquals("Ykbbp.'0pEs", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setVirtualNetworkId("");
      String string0 = cloudSubnetCreateRequest0.getVirtualNetworkId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setUsedIPCount("bxRUZ[<%+");
      String string0 = cloudSubnetCreateRequest0.getUsedIPCount();
      assertEquals("bxRUZ[<%+", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setUsedIPCount("");
      String string0 = cloudSubnetCreateRequest0.getUsedIPCount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setTags((List<NameValue>) null);
      List<NameValue> list0 = cloudSubnetCreateRequest0.getTags();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      LinkedList<NameValue> linkedList0 = new LinkedList<NameValue>();
      NameValue nameValue0 = new NameValue();
      linkedList0.add(nameValue0);
      cloudSubnetCreateRequest0.setTags(linkedList0);
      List<NameValue> list0 = cloudSubnetCreateRequest0.getTags();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      Integer integer0 = new Integer(0);
      hashMap0.put("IG;8&Dc\"^KkH", integer0);
      cloudSubnetCreateRequest0.setSubscribedIPUsage(hashMap0);
      Map<String, Integer> map0 = cloudSubnetCreateRequest0.getSubscribedIPUsage();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubscribedIPCount("");
      String string0 = cloudSubnetCreateRequest0.getSubscribedIPCount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubnetId("com.capitalone.dashboard.model.NameValue");
      String string0 = cloudSubnetCreateRequest0.getSubnetId();
      assertEquals("com.capitalone.dashboard.model.NameValue", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubnetId("");
      String string0 = cloudSubnetCreateRequest0.getSubnetId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setState("");
      String string0 = cloudSubnetCreateRequest0.getState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setState("");
      String string0 = cloudSubnetCreateRequest0.getState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setLastUpdateDate("7&2%nr[x");
      String string0 = cloudSubnetCreateRequest0.getLastUpdateDate();
      assertEquals("7&2%nr[x", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setLastUpdateDate("");
      String string0 = cloudSubnetCreateRequest0.getLastUpdateDate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      cloudSubnetCreateRequest0.setIpUsage(hashMap0);
      Map<String, Integer> map0 = cloudSubnetCreateRequest0.getIpUsage();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      Integer integer0 = new Integer(2086);
      hashMap0.put("- p7k-PR", integer0);
      cloudSubnetCreateRequest0.setIpUsage(hashMap0);
      Map<String, Integer> map0 = cloudSubnetCreateRequest0.getIpUsage();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setDefaultForZone(".");
      String string0 = cloudSubnetCreateRequest0.getDefaultForZone();
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setDefaultForZone("");
      String string0 = cloudSubnetCreateRequest0.getDefaultForZone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setCreationDate("com.capitalone.dashboard.model.NameValue");
      String string0 = cloudSubnetCreateRequest0.getCreationDate();
      assertEquals("com.capitalone.dashboard.model.NameValue", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setCreationDate("");
      String string0 = cloudSubnetCreateRequest0.getCreationDate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setCidrCount("t7#ov<DH)}[yPC$");
      String string0 = cloudSubnetCreateRequest0.getCidrCount();
      assertEquals("t7#ov<DH)}[yPC$", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setCidrCount("");
      String string0 = cloudSubnetCreateRequest0.getCidrCount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setCidrBlock("");
      String string0 = cloudSubnetCreateRequest0.getCidrBlock();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setAvailableIPCount("Ykbbp.'0pEs");
      String string0 = cloudSubnetCreateRequest0.getAvailableIPCount();
      assertEquals("Ykbbp.'0pEs", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setAvailableIPCount("");
      String string0 = cloudSubnetCreateRequest0.getAvailableIPCount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setAccountNumber("DWshr");
      String string0 = cloudSubnetCreateRequest0.getAccountNumber();
      assertEquals("DWshr", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      CloudSubnetCreateRequest cloudSubnetCreateRequest1 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubnetId("i+F<?x#0UE>Y8");
      boolean boolean0 = cloudSubnetCreateRequest0.equals(cloudSubnetCreateRequest1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubnetId("a$0^zG*BDx8");
      CloudSubnetCreateRequest cloudSubnetCreateRequest1 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest1.setSubnetId("a$0^zG*BDx8");
      // Undeclared exception!
      try { 
        cloudSubnetCreateRequest0.equals(cloudSubnetCreateRequest1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      boolean boolean0 = cloudSubnetCreateRequest0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      boolean boolean0 = cloudSubnetCreateRequest0.equals(cloudSubnetCreateRequest0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      boolean boolean0 = cloudSubnetCreateRequest0.equals("s`JFd)h_qx");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getZone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setCidrBlock("com.capitalone.dashboard.request.CloudSubnetCreateRequest");
      String string0 = cloudSubnetCreateRequest0.getCidrBlock();
      assertEquals("com.capitalone.dashboard.request.CloudSubnetCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getCidrCount();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getVirtualNetworkId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      Map<String, Integer> map0 = cloudSubnetCreateRequest0.getSubscribedIPUsage();
      assertNull(map0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getAvailableIPCount();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      List<NameValue> list0 = cloudSubnetCreateRequest0.getTags();
      cloudSubnetCreateRequest0.setTags(list0);
      assertNull(cloudSubnetCreateRequest0.getDefaultForZone());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setAccountNumber("");
      String string0 = cloudSubnetCreateRequest0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      Map<String, Integer> map0 = cloudSubnetCreateRequest0.getIpUsage();
      assertNull(map0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getSubscribedIPCount();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getLastUpdateDate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getCreationDate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getUsedIPCount();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getSubnetId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getDefaultForZone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      cloudSubnetCreateRequest0.setSubscribedIPUsage(hashMap0);
      Map<String, Integer> map0 = cloudSubnetCreateRequest0.getSubscribedIPUsage();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      cloudSubnetCreateRequest0.setSubscribedIPCount("");
      String string0 = cloudSubnetCreateRequest0.getSubscribedIPCount();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      CloudSubnetCreateRequest cloudSubnetCreateRequest0 = new CloudSubnetCreateRequest();
      String string0 = cloudSubnetCreateRequest0.getCidrBlock();
      assertNull(string0);
  }
}
