/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:05:21 GMT 2020
 */

package com.capitalone.dashboard.request;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.request.CloudSubnetListRefreshRequest;
import java.time.ZoneId;
import java.util.Collection;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CloudSubnetListRefreshRequest_ESTest extends CloudSubnetListRefreshRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add((String) null);
      cloudSubnetListRefreshRequest0.setSubnetIds(linkedList0);
      List<String> list0 = cloudSubnetListRefreshRequest0.getSubnetIds();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      LinkedList<Locale.LanguageRange> linkedList0 = new LinkedList<Locale.LanguageRange>();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) linkedList0, (Collection<String>) set0, locale_FilteringMode0);
      cloudSubnetListRefreshRequest0.setSubnetIds(list0);
      List<String> list1 = cloudSubnetListRefreshRequest0.getSubnetIds();
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      cloudSubnetListRefreshRequest0.setAccountNumber("Z=5]a-$e.W,t8O");
      String string0 = cloudSubnetListRefreshRequest0.getAccountNumber();
      assertEquals("Z=5]a-$e.W,t8O", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      cloudSubnetListRefreshRequest0.setAccountNumber("");
      String string0 = cloudSubnetListRefreshRequest0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      String string0 = cloudSubnetListRefreshRequest0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      Date date0 = cloudSubnetListRefreshRequest0.getRefreshDate();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      List<String> list0 = cloudSubnetListRefreshRequest0.getSubnetIds();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CloudSubnetListRefreshRequest cloudSubnetListRefreshRequest0 = new CloudSubnetListRefreshRequest();
      MockDate mockDate0 = new MockDate();
      cloudSubnetListRefreshRequest0.setRefreshDate(mockDate0);
      Date date0 = cloudSubnetListRefreshRequest0.getRefreshDate();
      assertEquals("Fri Feb 14 20:21:21 GMT 2014", date0.toString());
  }
}
