/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:10:40 GMT 2020
 */

package com.capitalone.dashboard.request;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.request.CloudVirtualNetworkListRefreshRequest;
import java.util.Collection;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CloudVirtualNetworkListRefreshRequest_ESTest extends CloudVirtualNetworkListRefreshRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst((String) null);
      cloudVirtualNetworkListRefreshRequest0.setVirtualNetworkIds(linkedList0);
      List<String> list0 = cloudVirtualNetworkListRefreshRequest0.getVirtualNetworkIds();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      LinkedList<Locale.LanguageRange> linkedList0 = new LinkedList<Locale.LanguageRange>();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) linkedList0, (Collection<String>) null);
      cloudVirtualNetworkListRefreshRequest0.setVirtualNetworkIds(list0);
      List<String> list1 = cloudVirtualNetworkListRefreshRequest0.getVirtualNetworkIds();
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      cloudVirtualNetworkListRefreshRequest0.setAccountNumber("");
      String string0 = cloudVirtualNetworkListRefreshRequest0.getAccountNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      Date date0 = cloudVirtualNetworkListRefreshRequest0.getRefreshDate();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      cloudVirtualNetworkListRefreshRequest0.setAccountNumber("C%JlV(=+");
      String string0 = cloudVirtualNetworkListRefreshRequest0.getAccountNumber();
      assertEquals("C%JlV(=+", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      String string0 = cloudVirtualNetworkListRefreshRequest0.getAccountNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      List<String> list0 = cloudVirtualNetworkListRefreshRequest0.getVirtualNetworkIds();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CloudVirtualNetworkListRefreshRequest cloudVirtualNetworkListRefreshRequest0 = new CloudVirtualNetworkListRefreshRequest();
      MockDate mockDate0 = new MockDate();
      cloudVirtualNetworkListRefreshRequest0.setRefreshDate(mockDate0);
      Date date0 = cloudVirtualNetworkListRefreshRequest0.getRefreshDate();
      assertSame(date0, mockDate0);
  }
}
