/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:11:02 GMT 2020
 */

package com.capitalone.dashboard.request;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.request.DeployDataCreateRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DeployDataCreateRequest_ESTest extends DeployDataCreateRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setStartedBy("P5*[");
      String string0 = deployDataCreateRequest0.getStartedBy();
      assertEquals("P5*[", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setStartedBy("");
      String string0 = deployDataCreateRequest0.getStartedBy();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setStartTime(2171L);
      long long0 = deployDataCreateRequest0.getStartTime();
      assertEquals(2171L, long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setStartTime((-633L));
      long long0 = deployDataCreateRequest0.getStartTime();
      assertEquals((-633L), long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setNiceName("YLXT~ s@Qqh");
      String string0 = deployDataCreateRequest0.getNiceName();
      assertEquals("YLXT~ s@Qqh", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setNiceName("");
      String string0 = deployDataCreateRequest0.getNiceName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setJobUrl("Kd/mF-`|Dquk-'l&xls");
      String string0 = deployDataCreateRequest0.getJobUrl();
      assertEquals("Kd/mF-`|Dquk-'l&xls", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setJobName("");
      String string0 = deployDataCreateRequest0.getJobName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setInstanceUrl("com.capitalone.dashboard.request.DeployDataCreateRequest");
      String string0 = deployDataCreateRequest0.getInstanceUrl();
      assertEquals("com.capitalone.dashboard.request.DeployDataCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setInstanceUrl("");
      String string0 = deployDataCreateRequest0.getInstanceUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setHygieiaId("?M7:)Ahs<M ,ZNY2S");
      String string0 = deployDataCreateRequest0.getHygieiaId();
      assertEquals("?M7:)Ahs<M ,ZNY2S", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setExecutionId("^`?=R*Ucq_>rM");
      String string0 = deployDataCreateRequest0.getExecutionId();
      assertEquals("^`?=R*Ucq_>rM", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setEnvName("D&/qBh]GO5t");
      String string0 = deployDataCreateRequest0.getEnvName();
      assertEquals("D&/qBh]GO5t", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setEndTime((-916L));
      long long0 = deployDataCreateRequest0.getEndTime();
      assertEquals((-916L), long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setDuration(727L);
      long long0 = deployDataCreateRequest0.getDuration();
      assertEquals(727L, long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setDuration((-1L));
      long long0 = deployDataCreateRequest0.getDuration();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setDeployStatus("aO$p4@J6SBN");
      String string0 = deployDataCreateRequest0.getDeployStatus();
      assertEquals("aO$p4@J6SBN", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setDeployStatus("");
      String string0 = deployDataCreateRequest0.getDeployStatus();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setCollectorName("ac#pmH[!");
      String string0 = deployDataCreateRequest0.getCollectorName();
      assertEquals("ac#pmH[!", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setArtifactVersion("");
      String string0 = deployDataCreateRequest0.getArtifactVersion();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setArtifactName("]4@$%!P6bS(");
      String string0 = deployDataCreateRequest0.getArtifactName();
      assertEquals("]4@$%!P6bS(", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setArtifactName("");
      String string0 = deployDataCreateRequest0.getArtifactName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setArtifactGroup("y01clRK*-j_r6JfWuci");
      String string0 = deployDataCreateRequest0.getArtifactGroup();
      assertEquals("y01clRK*-j_r6JfWuci", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setAppName("lD");
      String string0 = deployDataCreateRequest0.getAppName();
      assertEquals("lD", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setAppName("");
      String string0 = deployDataCreateRequest0.getAppName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getCollectorName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setArtifactVersion("com.capitalone.dashboard.request.DeployDataCreateRequest");
      String string0 = deployDataCreateRequest0.getArtifactVersion();
      assertEquals("com.capitalone.dashboard.request.DeployDataCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getStartedBy();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getInstanceUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      long long0 = deployDataCreateRequest0.getDuration();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setCollectorName("");
      String string0 = deployDataCreateRequest0.getCollectorName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setArtifactGroup("");
      String string0 = deployDataCreateRequest0.getArtifactGroup();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getJobUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getExecutionId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setJobName("com.capitalone.dashboard.request.DeployDataCreateRequest");
      String string0 = deployDataCreateRequest0.getJobName();
      assertEquals("com.capitalone.dashboard.request.DeployDataCreateRequest", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getArtifactVersion();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getDeployStatus();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getEnvName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getHygieiaId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      long long0 = deployDataCreateRequest0.getStartTime();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      long long0 = deployDataCreateRequest0.getEndTime();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setEndTime(1L);
      long long0 = deployDataCreateRequest0.getEndTime();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getJobName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setHygieiaId("");
      String string0 = deployDataCreateRequest0.getHygieiaId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getArtifactGroup();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setJobUrl("");
      String string0 = deployDataCreateRequest0.getJobUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getArtifactName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setExecutionId("");
      String string0 = deployDataCreateRequest0.getExecutionId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getAppName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      String string0 = deployDataCreateRequest0.getNiceName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      DeployDataCreateRequest deployDataCreateRequest0 = new DeployDataCreateRequest();
      deployDataCreateRequest0.setEnvName("");
      String string0 = deployDataCreateRequest0.getEnvName();
      assertEquals("", string0);
  }
}
