/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 09:56:43 GMT 2020
 */

package com.capitalone.dashboard.status;

import org.junit.Test;

public class DeployAuditStatus_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
