/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 13:20:10 GMT 2020
 */

package com.capitalone.dashboard.response;

import org.junit.Test;
import static org.junit.Assert.*;
import com.capitalone.dashboard.response.CloudSubNetworkAggregatedResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CloudSubNetworkAggregatedResponse_ESTest extends CloudSubNetworkAggregatedResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CloudSubNetworkAggregatedResponse cloudSubNetworkAggregatedResponse0 = new CloudSubNetworkAggregatedResponse();
  }
}
